// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorldExplorer
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Zoom : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Zoom\",\"namespace\":\"WorldExplorer\",\"fields\":[{\"name\":\"ide" +
				"ntifier\",\"type\":\"string\"},{\"name\":\"zoomdirection\",\"type\":{\"type\":\"enum\",\"name\":\"" +
				"Direction\",\"namespace\":\"WorldExplorer\",\"symbols\":[\"In\",\"Out\"]}}]}");
		private string _identifier;
		private WorldExplorer.Direction _zoomdirection;
		public virtual Schema Schema
		{
			get
			{
				return Zoom._SCHEMA;
			}
		}
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				this._identifier = value;
			}
		}
		public WorldExplorer.Direction zoomdirection
		{
			get
			{
				return this._zoomdirection;
			}
			set
			{
				this._zoomdirection = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.identifier;
			case 1: return this.zoomdirection;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.identifier = (System.String)fieldValue; break;
			case 1: this.zoomdirection = (WorldExplorer.Direction)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
