// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.worldexplorer
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Table : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Table"",""namespace"":""eu.driver.model.worldexplorer"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""xpos"",""type"":""float""},{""name"":""ypos"",""type"":""float""},{""name"":""zpos"",""type"":""float""},{""name"":""xrot"",""type"":""float""},{""name"":""yrot"",""type"":""float""},{""name"":""zrot"",""type"":""float""},{""name"":""xscale"",""type"":""float""},{""name"":""yscale"",""type"":""float""},{""name"":""zscale"",""type"":""float""}]}");
		private string _name;
		private float _xpos;
		private float _ypos;
		private float _zpos;
		private float _xrot;
		private float _yrot;
		private float _zrot;
		private float _xscale;
		private float _yscale;
		private float _zscale;
		public virtual Schema Schema
		{
			get
			{
				return Table._SCHEMA;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public float xpos
		{
			get
			{
				return this._xpos;
			}
			set
			{
				this._xpos = value;
			}
		}
		public float ypos
		{
			get
			{
				return this._ypos;
			}
			set
			{
				this._ypos = value;
			}
		}
		public float zpos
		{
			get
			{
				return this._zpos;
			}
			set
			{
				this._zpos = value;
			}
		}
		public float xrot
		{
			get
			{
				return this._xrot;
			}
			set
			{
				this._xrot = value;
			}
		}
		public float yrot
		{
			get
			{
				return this._yrot;
			}
			set
			{
				this._yrot = value;
			}
		}
		public float zrot
		{
			get
			{
				return this._zrot;
			}
			set
			{
				this._zrot = value;
			}
		}
		public float xscale
		{
			get
			{
				return this._xscale;
			}
			set
			{
				this._xscale = value;
			}
		}
		public float yscale
		{
			get
			{
				return this._yscale;
			}
			set
			{
				this._yscale = value;
			}
		}
		public float zscale
		{
			get
			{
				return this._zscale;
			}
			set
			{
				this._zscale = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.name;
			case 1: return this.xpos;
			case 2: return this.ypos;
			case 3: return this.zpos;
			case 4: return this.xrot;
			case 5: return this.yrot;
			case 6: return this.zrot;
			case 7: return this.xscale;
			case 8: return this.yscale;
			case 9: return this.zscale;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.name = (System.String)fieldValue; break;
			case 1: this.xpos = (System.Single)fieldValue; break;
			case 2: this.ypos = (System.Single)fieldValue; break;
			case 3: this.zpos = (System.Single)fieldValue; break;
			case 4: this.xrot = (System.Single)fieldValue; break;
			case 5: this.yrot = (System.Single)fieldValue; break;
			case 6: this.zrot = (System.Single)fieldValue; break;
			case 7: this.xscale = (System.Single)fieldValue; break;
			case 8: this.yscale = (System.Single)fieldValue; break;
			case 9: this.zscale = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
