// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace eu.driver.model.worldexplorer
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Zoom : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Zoom\",\"namespace\":\"eu.driver.model.worldexplorer\",\"field" +
				"s\":[{\"name\":\"zoomdirection\",\"type\":{\"type\":\"enum\",\"name\":\"Direction\",\"namespace\"" +
				":\"eu.driver.model.worldexplorer\",\"symbols\":[\"In\",\"Out\"]}}]}");
		private eu.driver.model.worldexplorer.Direction _zoomdirection;
		public virtual Schema Schema
		{
			get
			{
				return Zoom._SCHEMA;
			}
		}
		public eu.driver.model.worldexplorer.Direction zoomdirection
		{
			get
			{
				return this._zoomdirection;
			}
			set
			{
				this._zoomdirection = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.zoomdirection;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.zoomdirection = (eu.driver.model.worldexplorer.Direction)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
